/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module Riscv_core(clk, rstN, reset_pc_0, hart_id_0, ir_address, ir_valid, ir_data, ir_ready, imem_addr, imem_req, imem_rdata, imem_valid, dmem_addr, dmem_req, dmem_we, dmem_wdata, dmem_be, dmem_rdata, dmem_valid, timer_irq, soft_irq
, ext_irq);
  input clk;
  wire clk;
  input rstN;
  wire rstN;
  input [31:0] reset_pc_0;
  wire [31:0] reset_pc_0;
  input [31:0] hart_id_0;
  wire [31:0] hart_id_0;
  output [31:0] ir_address;
  wire [31:0] ir_address;
  output ir_valid;
  wire ir_valid;
  input [31:0] ir_data;
  wire [31:0] ir_data;
  input ir_ready;
  wire ir_ready;
  output [31:0] imem_addr;
  wire [31:0] imem_addr;
  output imem_req;
  wire imem_req;
  input [31:0] imem_rdata;
  wire [31:0] imem_rdata;
  input imem_valid;
  wire imem_valid;
  output [31:0] dmem_addr;
  wire [31:0] dmem_addr;
  output dmem_req;
  wire dmem_req;
  output dmem_we;
  wire dmem_we;
  output [31:0] dmem_wdata;
  wire [31:0] dmem_wdata;
  output [3:0] dmem_be;
  wire [3:0] dmem_be;
  input [31:0] dmem_rdata;
  wire [31:0] dmem_rdata;
  input dmem_valid;
  wire dmem_valid;
  input timer_irq;
  wire timer_irq;
  input soft_irq;
  wire soft_irq;
  input ext_irq;
  wire ext_irq;
  Riscv_hart Riscv_hart_inst_0 (
    .clk(clk),
    .dmem_addr(dmem_addr),
    .dmem_be(dmem_be),
    .dmem_rdata(dmem_rdata),
    .dmem_req(dmem_req),
    .dmem_valid(dmem_valid),
    .dmem_wdata(dmem_wdata),
    .dmem_we(dmem_we),
    .ext_irq(ext_irq),
    .hart_id(hart_id_0),
    .imem_addr(imem_addr),
    .imem_rdata(imem_rdata),
    .imem_req(imem_req),
    .imem_valid(imem_valid),
    .ir_address(ir_address),
    .ir_data(ir_data),
    .ir_ready(ir_ready),
    .ir_valid(ir_valid),
    .reset_pc(reset_pc_0),
    .rstN(rstN),
    .soft_irq(soft_irq),
    .timer_irq(timer_irq)
  );
endmodule

module Riscv_hart(clk, rstN, reset_pc, hart_id, ir_address, ir_valid, ir_ready, ir_data, imem_addr, imem_req, imem_rdata, imem_valid, dmem_addr, dmem_req, dmem_we, dmem_wdata, dmem_be, dmem_rdata, dmem_valid, timer_irq, soft_irq
, ext_irq);
  input clk;
  wire clk;
  input rstN;
  wire rstN;
  input [31:0] reset_pc;
  wire [31:0] reset_pc;
  input [31:0] hart_id;
  wire [31:0] hart_id;
  output [31:0] ir_address;
  wire [31:0] ir_address;
  output ir_valid;
  wire ir_valid;
  input ir_ready;
  wire ir_ready;
  input [31:0] ir_data;
  wire [31:0] ir_data;
  output [31:0] imem_addr;
  wire [31:0] imem_addr;
  output imem_req;
  wire imem_req;
  input [31:0] imem_rdata;
  wire [31:0] imem_rdata;
  input imem_valid;
  wire imem_valid;
  output [31:0] dmem_addr;
  wire [31:0] dmem_addr;
  output dmem_req;
  wire dmem_req;
  output dmem_we;
  wire dmem_we;
  output [31:0] dmem_wdata;
  wire [31:0] dmem_wdata;
  output [3:0] dmem_be;
  wire [3:0] dmem_be;
  input [31:0] dmem_rdata;
  wire [31:0] dmem_rdata;
  input dmem_valid;
  wire dmem_valid;
  input timer_irq;
  wire timer_irq;
  input soft_irq;
  wire soft_irq;
  input ext_irq;
  wire ext_irq;
  pipeline pipeline_inst (
    .clk(clk),
    .ir_address(ir_address),
    .ir_data(ir_data),
    .ir_ready(ir_ready),
    .ir_valid(ir_valid),
    .reset_pc(reset_pc),
    .rstN(rstN)
  );
  assign dmem_addr = 32'hxxxxxxxx;
  assign dmem_be = 4'hx;
  assign dmem_req = 1'hx;
  assign dmem_wdata = 32'hxxxxxxxx;
  assign dmem_we = 1'hx;
  assign imem_addr = 32'hxxxxxxxx;
  assign imem_req = 1'hx;
endmodule

module Riscv_synth_top(clk, rstN, reset_pc_0, hart_id_0, ir_address, ir_valid, ir_ready, imem_addr, imem_req, ir_data, imem_valid, dmem_addr, dmem_req, dmem_we, dmem_wdata, dmem_be, dmem_rdata, dmem_valid, timer_irq, soft_irq, ext_irq
);
  input clk;
  wire clk;
  input rstN;
  wire rstN;
  input [31:0] reset_pc_0;
  wire [31:0] reset_pc_0;
  input [31:0] hart_id_0;
  wire [31:0] hart_id_0;
  output [31:0] ir_address;
  wire [31:0] ir_address;
  output ir_valid;
  wire ir_valid;
  input ir_ready;
  wire ir_ready;
  output [31:0] imem_addr;
  wire [31:0] imem_addr;
  output imem_req;
  wire imem_req;
  input [31:0] ir_data;
  wire [31:0] ir_data;
  input imem_valid;
  wire imem_valid;
  output [31:0] dmem_addr;
  wire [31:0] dmem_addr;
  output dmem_req;
  wire dmem_req;
  output dmem_we;
  wire dmem_we;
  output [31:0] dmem_wdata;
  wire [31:0] dmem_wdata;
  output [3:0] dmem_be;
  wire [3:0] dmem_be;
  input [31:0] dmem_rdata;
  wire [31:0] dmem_rdata;
  input dmem_valid;
  wire dmem_valid;
  input timer_irq;
  wire timer_irq;
  input soft_irq;
  wire soft_irq;
  input ext_irq;
  wire ext_irq;
  Riscv_core Riscv_core_inst (
    .clk(clk),
    .ir_address(ir_address),
    .ir_data(ir_data),
    .ir_ready(ir_ready),
    .ir_valid(ir_valid),
    .reset_pc_0(reset_pc_0),
    .rstN(rstN)
  );
  assign dmem_addr = 32'hxxxxxxxx;
  assign dmem_be = 4'hx;
  assign dmem_req = 1'hx;
  assign dmem_wdata = 32'hxxxxxxxx;
  assign dmem_we = 1'hx;
  assign imem_addr = 32'hxxxxxxxx;
  assign imem_req = 1'hx;
endmodule

module fetch(clk, rstN, reset_pc, stall, ir_ready, ir_address, ir_valid, ir_data, decode_ir, decode_valid);
  input clk;
  wire clk;
  input rstN;
  wire rstN;
  input [31:0] reset_pc;
  wire [31:0] reset_pc;
  input stall;
  wire stall;
  input ir_ready;
  wire ir_ready;
  output [31:0] ir_address;
  wire [31:0] ir_address;
  output ir_valid;
  wire ir_valid;
  input [31:0] ir_data;
  wire [31:0] ir_data;
  output [31:0] decode_ir;
  reg [31:0] decode_ir;
  output decode_valid;
  wire decode_valid;
  wire [29:0] _000_;
  wire [29:0] _001_;
  wire [29:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  reg [31:0] pc_q;
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[2] <= reset_pc[2];
    else if (ir_ready) pc_q[2] <= _001_[0];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[3] <= reset_pc[3];
    else if (ir_ready) pc_q[3] <= _002_[1];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[4] <= reset_pc[4];
    else if (ir_ready) pc_q[4] <= _002_[2];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[5] <= reset_pc[5];
    else if (ir_ready) pc_q[5] <= _002_[3];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[6] <= reset_pc[6];
    else if (ir_ready) pc_q[6] <= _002_[4];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[7] <= reset_pc[7];
    else if (ir_ready) pc_q[7] <= _002_[5];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[8] <= reset_pc[8];
    else if (ir_ready) pc_q[8] <= _002_[6];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[9] <= reset_pc[9];
    else if (ir_ready) pc_q[9] <= _002_[7];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[10] <= reset_pc[10];
    else if (ir_ready) pc_q[10] <= _002_[8];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[11] <= reset_pc[11];
    else if (ir_ready) pc_q[11] <= _002_[9];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[12] <= reset_pc[12];
    else if (ir_ready) pc_q[12] <= _002_[10];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[13] <= reset_pc[13];
    else if (ir_ready) pc_q[13] <= _002_[11];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[14] <= reset_pc[14];
    else if (ir_ready) pc_q[14] <= _002_[12];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[15] <= reset_pc[15];
    else if (ir_ready) pc_q[15] <= _002_[13];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[16] <= reset_pc[16];
    else if (ir_ready) pc_q[16] <= _002_[14];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[17] <= reset_pc[17];
    else if (ir_ready) pc_q[17] <= _002_[15];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[18] <= reset_pc[18];
    else if (ir_ready) pc_q[18] <= _002_[16];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[19] <= reset_pc[19];
    else if (ir_ready) pc_q[19] <= _002_[17];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[20] <= reset_pc[20];
    else if (ir_ready) pc_q[20] <= _002_[18];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[21] <= reset_pc[21];
    else if (ir_ready) pc_q[21] <= _002_[19];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[22] <= reset_pc[22];
    else if (ir_ready) pc_q[22] <= _002_[20];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[23] <= reset_pc[23];
    else if (ir_ready) pc_q[23] <= _002_[21];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[24] <= reset_pc[24];
    else if (ir_ready) pc_q[24] <= _002_[22];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[25] <= reset_pc[25];
    else if (ir_ready) pc_q[25] <= _002_[23];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[26] <= reset_pc[26];
    else if (ir_ready) pc_q[26] <= _002_[24];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[27] <= reset_pc[27];
    else if (ir_ready) pc_q[27] <= _002_[25];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[28] <= reset_pc[28];
    else if (ir_ready) pc_q[28] <= _002_[26];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[29] <= reset_pc[29];
    else if (ir_ready) pc_q[29] <= _002_[27];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[30] <= reset_pc[30];
    else if (ir_ready) pc_q[30] <= _002_[28];
  always @(posedge clk, negedge rstN)
    if (!rstN) pc_q[31] <= reset_pc[31];
    else if (ir_ready) pc_q[31] <= _002_[29];
  always @*
    if (!rstN) pc_q[0] = reset_pc[0];
  always @*
    if (!rstN) pc_q[1] = reset_pc[1];
  always @(posedge clk)
    if (_003_) decode_ir[0] <= ir_data[0];
  always @(posedge clk)
    if (_003_) decode_ir[1] <= ir_data[1];
  always @(posedge clk)
    if (_003_) decode_ir[2] <= ir_data[2];
  always @(posedge clk)
    if (_003_) decode_ir[3] <= ir_data[3];
  always @(posedge clk)
    if (_003_) decode_ir[4] <= ir_data[4];
  always @(posedge clk)
    if (_003_) decode_ir[5] <= ir_data[5];
  always @(posedge clk)
    if (_003_) decode_ir[6] <= ir_data[6];
  always @(posedge clk)
    if (_003_) decode_ir[7] <= ir_data[7];
  always @(posedge clk)
    if (_003_) decode_ir[8] <= ir_data[8];
  always @(posedge clk)
    if (_003_) decode_ir[9] <= ir_data[9];
  always @(posedge clk)
    if (_003_) decode_ir[10] <= ir_data[10];
  always @(posedge clk)
    if (_003_) decode_ir[11] <= ir_data[11];
  always @(posedge clk)
    if (_003_) decode_ir[12] <= ir_data[12];
  always @(posedge clk)
    if (_003_) decode_ir[13] <= ir_data[13];
  always @(posedge clk)
    if (_003_) decode_ir[14] <= ir_data[14];
  always @(posedge clk)
    if (_003_) decode_ir[15] <= ir_data[15];
  always @(posedge clk)
    if (_003_) decode_ir[16] <= ir_data[16];
  always @(posedge clk)
    if (_003_) decode_ir[17] <= ir_data[17];
  always @(posedge clk)
    if (_003_) decode_ir[18] <= ir_data[18];
  always @(posedge clk)
    if (_003_) decode_ir[19] <= ir_data[19];
  always @(posedge clk)
    if (_003_) decode_ir[20] <= ir_data[20];
  always @(posedge clk)
    if (_003_) decode_ir[21] <= ir_data[21];
  always @(posedge clk)
    if (_003_) decode_ir[22] <= ir_data[22];
  always @(posedge clk)
    if (_003_) decode_ir[23] <= ir_data[23];
  always @(posedge clk)
    if (_003_) decode_ir[24] <= ir_data[24];
  always @(posedge clk)
    if (_003_) decode_ir[25] <= ir_data[25];
  always @(posedge clk)
    if (_003_) decode_ir[26] <= ir_data[26];
  always @(posedge clk)
    if (_003_) decode_ir[27] <= ir_data[27];
  always @(posedge clk)
    if (_003_) decode_ir[28] <= ir_data[28];
  always @(posedge clk)
    if (_003_) decode_ir[29] <= ir_data[29];
  always @(posedge clk)
    if (_003_) decode_ir[30] <= ir_data[30];
  always @(posedge clk)
    if (_003_) decode_ir[31] <= ir_data[31];
  assign _002_[1] = pc_q[3] ^ pc_q[2];
  assign _002_[2] = pc_q[4] ^ _000_[1];
  assign _002_[3] = pc_q[5] ^ _000_[2];
  assign _002_[4] = pc_q[6] ^ _000_[3];
  assign _002_[5] = pc_q[7] ^ _000_[4];
  assign _002_[6] = pc_q[8] ^ _000_[5];
  assign _002_[7] = pc_q[9] ^ _000_[6];
  assign _002_[8] = pc_q[10] ^ _000_[7];
  assign _002_[9] = pc_q[11] ^ _000_[8];
  assign _002_[10] = pc_q[12] ^ _000_[9];
  assign _002_[11] = pc_q[13] ^ _000_[10];
  assign _002_[12] = pc_q[14] ^ _000_[11];
  assign _002_[13] = pc_q[15] ^ _000_[12];
  assign _002_[14] = pc_q[16] ^ _000_[13];
  assign _002_[15] = pc_q[17] ^ _000_[14];
  assign _002_[16] = pc_q[18] ^ _000_[15];
  assign _002_[17] = pc_q[19] ^ _000_[16];
  assign _002_[18] = pc_q[20] ^ _000_[17];
  assign _002_[19] = pc_q[21] ^ _000_[18];
  assign _002_[20] = pc_q[22] ^ _000_[19];
  assign _002_[21] = pc_q[23] ^ _000_[20];
  assign _002_[22] = pc_q[24] ^ _000_[21];
  assign _002_[23] = pc_q[25] ^ _000_[22];
  assign _002_[24] = pc_q[26] ^ _000_[23];
  assign _002_[25] = pc_q[27] ^ _000_[24];
  assign _002_[26] = pc_q[28] ^ _000_[25];
  assign _002_[27] = pc_q[29] ^ _000_[26];
  assign _002_[28] = pc_q[30] ^ _000_[27];
  assign _002_[29] = pc_q[31] ^ _000_[28];
  assign _000_[28] = pc_q[30] & _000_[27];
  assign _000_[26] = pc_q[28] & _000_[25];
  assign _000_[24] = pc_q[26] & _000_[23];
  assign _000_[22] = pc_q[24] & _000_[21];
  assign _000_[20] = pc_q[22] & _000_[19];
  assign _000_[18] = pc_q[20] & _000_[17];
  assign _000_[16] = pc_q[18] & _000_[15];
  assign _000_[14] = pc_q[16] & _000_[13];
  assign _000_[12] = pc_q[14] & _000_[11];
  assign _000_[10] = pc_q[12] & _000_[9];
  assign _000_[8] = pc_q[10] & _000_[7];
  assign _000_[6] = pc_q[8] & _000_[5];
  assign _000_[4] = pc_q[6] & _000_[3];
  assign _000_[2] = pc_q[4] & _000_[1];
  assign _000_[25] = _015_ & _000_[23];
  assign _000_[21] = _013_ & _000_[19];
  assign _000_[17] = _011_ & _000_[15];
  assign _000_[13] = _009_ & _000_[11];
  assign _000_[9] = _007_ & _000_[7];
  assign _000_[5] = _005_ & _000_[3];
  assign _000_[27] = _022_ & _000_[23];
  assign _000_[19] = _020_ & _000_[15];
  assign _000_[11] = _018_ & _000_[7];
  assign _000_[23] = _024_ & _000_[15];
  assign _024_ = _021_ & _020_;
  assign _023_ = _019_ & _018_;
  assign _022_ = _016_ & _015_;
  assign _021_ = _014_ & _013_;
  assign _020_ = _012_ & _011_;
  assign _019_ = _010_ & _009_;
  assign _018_ = _008_ & _007_;
  assign _017_ = _006_ & _005_;
  assign _016_ = pc_q[29] & pc_q[28];
  assign _015_ = pc_q[27] & pc_q[26];
  assign _014_ = pc_q[25] & pc_q[24];
  assign _013_ = pc_q[23] & pc_q[22];
  assign _012_ = pc_q[21] & pc_q[20];
  assign _011_ = pc_q[19] & pc_q[18];
  assign _010_ = pc_q[17] & pc_q[16];
  assign _009_ = pc_q[15] & pc_q[14];
  assign _008_ = pc_q[13] & pc_q[12];
  assign _007_ = pc_q[11] & pc_q[10];
  assign _006_ = pc_q[9] & pc_q[8];
  assign _005_ = pc_q[7] & pc_q[6];
  assign _004_ = pc_q[5] & pc_q[4];
  assign _000_[15] = _023_ & _000_[7];
  assign _000_[7] = _017_ & _000_[3];
  assign _000_[3] = _004_ & _000_[1];
  assign _000_[1] = pc_q[3] & pc_q[2];
  assign _003_ = rstN & ir_ready;
  assign _001_[0] = ~pc_q[2];
  assign _002_[0] = _001_[0];
  assign _000_[0] = pc_q[2];
  assign _001_[29:1] = pc_q[31:3];
  assign decode_valid = 1'h1;
  assign ir_address = pc_q;
  assign ir_valid = 1'h1;
endmodule

module pipeline(clk, rstN, reset_pc, ir_data, ir_address, ir_valid, ir_ready);
  input clk;
  wire clk;
  input rstN;
  wire rstN;
  input [31:0] reset_pc;
  wire [31:0] reset_pc;
  input [31:0] ir_data;
  wire [31:0] ir_data;
  output [31:0] ir_address;
  wire [31:0] ir_address;
  output ir_valid;
  wire ir_valid;
  input ir_ready;
  wire ir_ready;
  fetch fetch_inst (
    .clk(clk),
    .ir_address(ir_address),
    .ir_data(ir_data),
    .ir_ready(ir_ready),
    .ir_valid(ir_valid),
    .reset_pc(reset_pc),
    .rstN(rstN)
  );
endmodule
